#!/usr/bin/env python3
"""check_metrics_drift.py — build gate: platform-scale claims must match data/metrics.json.

Content pages hardcode their numbers (only the homepage template and llms.txt
read METRICS), so corpus-scale claims drift as the pipeline grows: by 2026-07-03
the site carried every vintage from "2,300+" to "3,400+" municipalities against
a canonical 3,900+. This gate fails the build when a page carries a
platform-scale claim that diverges from the current data/metrics.json.

What counts as a platform-scale claim (scoped analysis numbers stay untouched):
  - N municipalities/towns/munis/jurisdictions, N >= 2,000
  - N documents / public records,             N >= 100,000
  - N signals,                                N >= 100,000
  - N tickers,                                N >= 100 (exact match required)

Pass rules:
  - Numeric match with any canonical value passes.
  - Understatement within 10% of canonical passes (weekly metrics bumps should
    not force a 30-page sweep) — EXCEPT tickers, which is exact.
  - Overstatement always fails (Commandment I: never claim more than the data).
  - A line containing the literal marker `metrics-ok` is waived (use for
    deliberately scoped or historical numbers the patterns can't distinguish).

Exempt files (deliberately historical or generated snapshots):
  - town-*-YYYY-MM-DD.md dated weekly digests
  - update-YYYY-MM.md monthly investor updates
  - prospect-*.md (generated by gen_prospect_page.py with as-of-generation
    numbers; the fix path is regeneration, not hand-editing)

Exit non-zero on violations — this is a fail-closed gate, not a diagnostic.
"""
import json
import re
import sys
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent
METRICS_FILE = BASE / "data" / "metrics.json"

EXEMPT = re.compile(r"(town-[a-z0-9-]+-\d{4}-\d{2}-\d{2}\.md|update-\d{4}-\d{2}\.md|prospect-[a-z0-9-]+\.md)$")

# (regex, metric keys the claim may match, floor below which the number is
# treated as scoped/story-level and ignored, exact_only)
TAG_RE = re.compile(r"<[^>]+>")
PATTERNS = [
    (re.compile(r"(\d[\d,]*)\+?\s+(?:US |U\.S\. |American )?(?:municipalities|towns|munis|jurisdictions)\b", re.I),
     ("municipalities",), 2000, False),
    (re.compile(r"(\d[\d,]*)\+?\s+(?:public\s+)?(?:documents|records)\b", re.I),
     ("documents", "signals", "permits"), 100_000, False),
    (re.compile(r"(\d[\d,]*)\+?\s+(?:classified\s+)?signals\b", re.I),
     ("signals",), 100_000, False),
    (re.compile(r"(\d[\d,]*)\+?\s+(?:resolved\s+|public\s+)?tickers\b", re.I),
     ("tickers",), 100, True),
]


def numeric(display: str) -> int:
    m = re.search(r"[\d,]+", display)
    return int(m.group(0).replace(",", "")) if m else 0


def main() -> int:
    metrics = json.loads(METRICS_FILE.read_text())
    canonical = {k: numeric(str(v)) for k, v in metrics.items() if numeric(str(v))}

    targets = [p for p in sorted((BASE / "content" / "pages").glob("*.md"))
               if not EXEMPT.search(p.name)]
    targets.append(BASE / "content" / "extra" / "towers" / "index.html")

    violations = []
    for path in targets:
        if not path.exists():
            continue
        for lineno, line in enumerate(path.read_text().splitlines(), 1):
            if "metrics-ok" in line:
                continue
            text = TAG_RE.sub(" ", line)
            for pat, keys, floor, exact in PATTERNS:
                for m in pat.finditer(text):
                    claim = int(m.group(1).replace(",", ""))
                    if claim < floor:
                        continue
                    ok = False
                    for key in keys:
                        canon = canonical.get(key)
                        if canon is None:
                            continue
                        if claim == canon:
                            ok = True
                        elif not exact and canon * 0.9 <= claim < canon:
                            ok = True  # small understatement, metrics moved
                    if not ok:
                        rel = path.relative_to(BASE)
                        expect = " / ".join(
                            f"{k}={metrics[k]}" for k in keys if k in metrics)
                        violations.append(
                            f"{rel}:{lineno}: claim {m.group(0).strip()!r} "
                            f"diverges from metrics.json ({expect})")

    if violations:
        print("METRICS DRIFT — platform-scale claims out of sync with data/metrics.json:")
        for v in violations:
            print(f"  {v}")
        print(f"\n{len(violations)} violation(s). Update the claim, regenerate "
              f"the page, or append `metrics-ok` (in a comment) to a "
              f"deliberately scoped line.")
        return 1
    print(f"metrics-drift: clean ({len(targets)} files checked against "
          f"metrics.json updated {metrics.get('updated', '?')})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
